[package]
name = "zkvm_support"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "=1.0.1"
hex = "0.4.3"
rand = "0.7.0"
# solana-sdk = { path = "../../agave/sdk", version = "=2.1.0" , features = ["borsh"] }
